//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencijaZaNekretnineMVC.Models.RepositoryEF
{
    using AgencijaZaNekretnineMVC.Models.Extensions;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class NekretninaModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NekretninaModel()
        {
            this.ZakazivanjeGledanjaNekretnines = new HashSet<ZakazivanjeGledanjaNekretnineModel>();
        }
    
        public int NekretninaID { get; set; }
        public string Adresa { get; set; }
        public string Opstina { get; set; }
        public Nullable<int> Spratnost { get; set; }
        public Nullable<double> Povrsina { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public string Namestenost { get; set; }
        public string VrstaNekretnine { get; set; }
        public string Struktura { get; set; }
        public string Stanje { get; set; }
        public Nullable<int> Sprat { get; set; }
        public string DodatneKarakteristike { get; set; }
        public string Napomena { get; set; }
        public string NekretnineSlike
        {
            get => JsonConvert.SerializeObject(Slike);
            set => Slike = JsonConvert.DeserializeObject<List<Slika>>(value);
        }

        public Nullable<int> VlasnikID { get; set; }
    
        public virtual OsobaModel Osoba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakazivanjeGledanjaNekretnineModel> ZakazivanjeGledanjaNekretnines { get; set; }

        [NotMapped]
        public List<Slika> Slike { get; set; }
    }
}
