//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencijaZaNekretnineMVC.Models.RepositoryEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OsobaModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OsobaModel()
        {
            this.Nekretninas = new HashSet<NekretninaModel>();
            this.ZakazivanjeGledanjaNekretnines = new HashSet<ZakazivanjeGledanjaNekretnineModel>();
        }
    
        public int OsobaID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string KorisnickoIme { get; set; }
        public string Sifra { get; set; }
        public string Pol { get; set; }
        public string JMBG { get; set; }
        public string BrojLicneKarte { get; set; }
        public string Adresa { get; set; }
        public string BrojMobilnog { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NekretninaModel> Nekretninas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakazivanjeGledanjaNekretnineModel> ZakazivanjeGledanjaNekretnines { get; set; }
    }
}
