//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencijaZaNekretnineMVC.Models.RepositoryEF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ZakazivanjeGledanjaNekretnineModel
    {
        public int ZakazivanjeID { get; set; }
        public Nullable<System.DateTime> DatumVreme { get; set; }
        public Nullable<int> NekretninaID { get; set; }
        public Nullable<int> KupacID { get; set; }
        [ForeignKey(nameof(NekretninaID))]
        public virtual NekretninaModel Nekretnina { get; set; }
        [ForeignKey(nameof(KupacID))]
        public virtual OsobaModel Osoba { get; set; }
    }
}
